### ISSUE TITLE
 Привет. Нужно связаться с ментором thewillwillhelp по поводу собеседования в Rsschool,прошу отписаться или добавить контакты в свой аккаунт Гита

### ISSUE THREAD

**Issue by tomsonst** [thewillwillhelp/godot-td#14]
Привет. Нужно связаться  с ментором thewillwillhelp по поводу собеседования в Rsschool,прошу отписаться или добавить контакты в свой аккаунт Гита

**Comment by thewillwillhelp** [comment]
The request was sent in discord

**Comment by tomsonst** [comment]
все ок
